### ISSUE TITLE
word2id1.pkl 文件

### ISSUE THREAD

**Issue by YuanCoder** [StephenLee2016/named_entity_recogonize#1]
word2id1.pkl 文件里主要是一些汉语常用字  每个字对应一个数字   这个有什么工具生成吗，谢谢

**Comment by StephenLee2016** [comment]
> word2id1.pkl文件里主要是一些汉语常用字每个字对应一个数字这个有什么工具生成吗，谢谢

你可以使用data.py生成这个文件，也可以自己实现。

**Comment by YuanCoder** [comment]
好的 谢谢
